### ISSUE TITLE
cachePath on cache provider

### ISSUE THREAD

**Issue by SalvoDiFede** [tgjones/dynamic-image#11]
Hi! It seems cachePath attributes want be recognized.

Sorry but i'm new on github: maybe you simply need to (re)add something like this, on Configuration/CachingSettings.cs ?

[ConfigurationProperty("cachePath")]
        public string cachePath
        {
            get { return this["cachePath"] as string; }
            set { this["cachePath"] = value; }
        }

**Comment by tgjones** [comment]
Thank you - good spot. I'm closing this because you've submitted #12 which fixes this.

**Comment by SalvoDiFede** [comment]
Yes.
