### ISSUE TITLE
Generated url does not load image

### ISSUE THREAD

**Issue by adjdred** [tgjones/dynamic-image#16]
Hi 

I have converted the App_Start class to be in vb.net and currently able to cache the images in App_Data. When trying to view the image using the url generated by DynamicImage class the image fails to load.

Are there any routes that I need to add to the site or am I able to override the cache location and url path generated by DynamicImage?

I am also using MVC5 but not the MVC method of loading the image.

Thanks

**Comment by AntjeReichenberger** [comment]
Did you ever figure out a solution to this. The cached image is stored in the correct folder but then retrieving the image URL I get /Assets/Images/DynamicImages/

Thanks for any replies.

**Comment by adjdred** [comment]
You need to add the below to your web.config

<system.webServer>
  <modules runAllManagedModulesForAllRequests="true" />
</system.webServer>
