### ISSUE TITLE
DynamicImage helper not available in @HTML 

### ISSUE THREAD

**Issue by chadneiro** [tgjones/dynamic-image#17]
I did the installation and it put in the DynamicImage file in the App_Start folder, but I can't find the helper in the @Html menu. Is there something else I have to do. I'm using MVC 5

**Comment by tgjones** [comment]
You also need to register the namespaces in your `Views/web.config` file. Have a look at [the example website's Views/web.config file](https://github.com/tgjones/dynamic-image/blob/master/src/SoundInTheory.DynamicImage.Website/Views/Web.config) for an example.
