### ISSUE TITLE
Get Byte[] from GeneratedImage

### ISSUE THREAD

**Issue by buaziz** [tgjones/dynamic-image#18]
I am using the object module to create an image from different layers, and after am done i want to save it back to the DB as a Byte[]. 

How do I accomplish this, as I do not see any method from GeneratedImage class, and the documented option was to get a URL.

thanks for the great library.

**Comment by tgjones** [comment]
If you're using the fluent API, you can get a `BitmapSource` object using the instructions at the bottom of this page:
http://dynamicimage.apphb.com/gettingstarted/fluentapi

``` csharp
BitmapSource bitmap = builder.GetImage();
```

If you're using the object model directly, then you can do:

``` csharp
BitmapSource bitmap = composition.GenerateImage().Image;
```

From there you can follow any method to get a `byte[]` from a `BitmapSource`, such as:
http://stackoverflow.com/a/11085124/208817

**Comment by buaziz** [comment]
thanks.
