### ISSUE TITLE
Generate thumbnail from pdf in a different domain

### ISSUE THREAD

**Issue by AmilaDotDev** [tgjones/dynamic-image#25]
Hi, 

I use PdfLayerBuilder to generate thumbnails of pdf files. These files are in my own domain and it works all good. But, now I have the requirement of generating thumbnails from pdfs in a different domain. Is it possible to do using DynamicImage library? or is there any other way to achieve this.

Thanks

**Comment by tgjones** [comment]
Currently, `PdfLayer` expects the source file to be on the local file system. Are you asking if it's possible for `PdfLayer` to retrieve PDFs over http? Or from a network share?

**Comment by AmilaDotDev** [comment]
I have to retrieve the pdf over http.

**Comment by tgjones** [comment]
I would suggest it would be better for you to do that retrieval in your own code. As far as I know, Ghostscript, the underlying API used to render the PDF, requires the PDF to be on the local file system, so either DynamicImage or your code needs to first download it over http and save it somewhere.

I'd suggest inheriting your own class from `PdfLayer`, something like this:

``` csharp
public class RemotePdfLayer : PdfLayer
{
    public string RemoteUrl
    {
        get { return this["RemoteUrl"] as string ?? string.Empty; }
        set { this["RemoteUrl"] = value; }
    }

    protected override void CreateImage(ImageGenerationContext context)
    {
        // TODO: Download PDF from RemoteUrl
        // TODO: Save PDF to temporary file
        // TODO: Set SourceFileName to temporary file

        // ... and then call the base class to do the PDF -> image conversion.
        base.CreateImage(context);
    }
}
```

**Comment by AmilaDotDev** [comment]
Yeah, that's what I plan to implement now. I just wanted to check if there was a better solution/Approach. 
Thanks for your replies Tim. I'm going to close this issue. Thanks again.
