### ISSUE TITLE
Saved image is black

### ISSUE THREAD

**Issue by katalinsocotar** [tgjones/dynamic-image#28]
Hi,
I used the following code, and the saved image is black:

`CompositionBuilder builder = new CompositionBuilder();
  builder.WithLayer(LayerBuilder.Image.SourceBytes(streamToResize)) .WithGlobalFilter(FilterBuilder.Resize.To(newWidth, newHeight, ResizeMode.UniformFill));
  builder.SaveTo(saveToPath);`

Have you any idea why the image is black?

Thanks!

![picture](https://user-images.githubusercontent.com/32196035/30742643-b3b1e89a-9fa2-11e7-8382-76f7158f9cba.jpg)

**Comment by potumati** [comment]
I'm having same problem, but my image is a transparent PNG.

This problem started on last week, before that was all ok.

`  var endereco = "http://www.pudim.com.br/";
        var imageUrl = new CompositionBuilder().ImageFormat(DynamicImageFormat.Png).WithLayer(new WebsiteScreenshotLayerBuilder().WebsiteUrl(endereco).Timeout(10000));
        var imagem = Server.MapPath("teste.png");
        imageUrl.SaveTo(imagem);`

![teste](https://user-images.githubusercontent.com/32221653/30773582-7ddef790-a041-11e7-8f48-c3038fb37f8c.png)

**Comment by katalinsocotar** [comment]
I can confirm that this worked for me too.

**Comment by tgjones** [comment]
Looks like this was a bug in a Windows Update:
https://support.microsoft.com/en-us/help/4043601/rendering-issues-after-the-september-12-2017-net-security-and-quality
