### ISSUE TITLE
dynamic-image for .NET 3.5

### ISSUE THREAD

**Issue by k09** [tgjones/dynamic-image#9]
Hi.
I am using your library to create thumbnails for each page of .pdf-files.
Something like this (where variable file is of type File (my own class)):

using SoundInTheory.DynamicImage;
using SoundInTheory.DynamicImage.Fluent;

Composition composition = new Composition();
for (int page = 1; page <= file.PageCount; page++)
{
    .PdfLayerBuilder pdfLayerBuilder = new PdfLayerBuilder().SourceFileName(file.PathPDF).PageNumber(page);
    composition.Layers.Add(pdfLayerBuilder.ToLayer());
    GeneratedImage bitmap = composition.GenerateImage();
    ///.......
}

My only problem is that the program hosting this is a WinForms client for .NET framework 3.5.
Since I am only using part of your library would it work for me build for .NET 3.5 and simply comment out lines preventing build?
Do you have any recommendations to solve this problem?

Best regards, Kristján

**Comment by k09** [comment]
I simply changed target framework to 3.5, commented out lots of code, moved a few lines around until I got a build. It works: I now have a (limited) version for .NET 3.5.

**Comment by tgjones** [comment]
Well done on getting it working! I don't plan to "officially" support .NET 3.5 though. You've proved that it's at least possible, but I think it would be a fair amount of work to get everything working. I'd have to provide an alternative for the newly-introduced async image generation. WPF 4 also introduced some improvements to pixel shaders and text rendering that I wouldn't want to lose - of course, I could compile multiple versions, but that adds to the maintenance cost.

So I'll close this for now, but I'll keep an eye out for more requests for a .NET 3.5 version.
